/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo1 {
    private var real: Int=0
    private var imagin: Int=0
    override fun toString():String{
        return "(${real}, ${imagin})"
    }
    }

fun main() {
    var complejo: Complejo1
    complejo= Complejo1()
    println("Mi complejo ${complejo.toString()}")
}
